# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

tasks:
  example-subscribe:
    dir: ./examples
    cmds:
      - go run ./subscribe/
  example-publish:
    dir: ./examples
    cmds:
      - go run ./publish_event/
